<?php

$images = array (
    array("title"=>"Barley Sunset",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 0,
        "thumbnail"=>"style/assets/thumbnails/barley_sunset.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/barley_sunset.jpg",
        "full-image"=>"style/assets/full-web/barley_sunset.jpg"),
    array("title"=>"Barnacle Breeze",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 1,
        "thumbnail"=>"style/assets/thumbnails/barnacle_breeze.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/barnacle_breeze.jpg",
        "full-image"=>"style/assets/full-web/barnacle_breeze.jpg"),
    array("title"=>"Blanket of Snow",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 2,
        "thumbnail"=>"style/assets/thumbnails/blanket_of_snow.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/blanket_of_snow.jpg",
        "full-image"=>"style/assets/full-web/blanket_of_snow.jpg"),    
    array("title"=>"Blossom",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 3,
        "thumbnail"=>"style/assets/thumbnails/blossom.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/blossom.jpg",
        "full-image"=>"style/assets/full-web/blossom.jpg"),    
    array("title"=>"Branch Shadow",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 4,
        "thumbnail"=>"style/assets/thumbnails/branch_shadow.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/branch_shadow.jpg",
        "full-image"=>"style/assets/full-web/branch_shadow.jpg"), 
    array("title"=>"Britanna Views",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 5,
        "thumbnail"=>"style/assets/thumbnails/britanna_views.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/britanna_views.jpg",
        "full-image"=>"style/assets/full-web/britanna_views.jpg"),    
    array("title"=>"Castle View",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 6,
        "thumbnail"=>"style/assets/thumbnails/castle_view.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/castle_view.jpg",
        "full-image"=>"style/assets/full-web/castle_view.jpg"),    
    array("title"=>"Dunwich Beach",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 7,
        "thumbnail"=>"style/assets/thumbnails/dunwich_beach.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/dunwich_beach.jpg",
        "full-image"=>"style/assets/full-web/dunwich_beach.jpg"),    
    array("title"=>"Dunwich Fisherman Hut",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 8,
        "thumbnail"=>"style/assets/thumbnails/dunwich_fishermans_hut.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/dunwich_fishermans_hut.jpg",
        "full-image"=>"style/assets/full-web/dunwich_fishermans_hut.jpg"),    
    array("title"=>"Erosion",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 9,
        "thumbnail"=>"style/assets/thumbnails/erosion.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/erosion.jpg",
        "full-image"=>"style/assets/full-web/erosion.jpg"),    
    array("title"=>"Fence View",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 10,
        "thumbnail"=>"style/assets/thumbnails/fence_view.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/fence_view.jpg",
        "full-image"=>"style/assets/full-web/fence_view.jpg"),    
    array("title"=>"Frinton Beach",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 11,
        "thumbnail"=>"style/assets/thumbnails/frinton_beach.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/frinton_beach.jpg",
        "full-image"=>"style/assets/full-web/frinton_beach.jpg"),    
    array("title"=>"Frinton Views",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 12,
        "thumbnail"=>"style/assets/thumbnails/frinton_views.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/frinton_views.jpg",
        "full-image"=>"style/assets/full-web/frinton_views.jpg"),    
    array("title"=>"Harvest Storm",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 13,
        "thumbnail"=>"style/assets/thumbnails/harvest_storm.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/harvest_storm.jpg",
        "full-image"=>"style/assets/full-web/harvest_storm.jpg"),    
    array("title"=>"Holkham Dunes",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 14,
        "thumbnail"=>"style/assets/thumbnails/holkham_dunes.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/holkham_dunes.jpg",
        "full-image"=>"style/assets/full-web/holkham_dunes.jpg"),    
    array("title"=>"Holkham Sea",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 15,
        "thumbnail"=>"style/assets/thumbnails/holkham_sea.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style//assets/half-web/holkham_sea.jpg",
        "full-image"=>"style/assets/full-web/holkham_sea.jpg"),    
    array("title"=>"Holkham Swell",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 16,
        "thumbnail"=>"style/assets/thumbnails/holkham_swell.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/holkham_swell.jpg",
        "full-image"=>"style/assets/full-web/holkham_swell.jpg"),    
    array("title"=>"Holkham Wood",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 17,
        "thumbnail"=>"style/assets/thumbnails/holkham_wood.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/holkham_wood.jpg",
        "full-image"=>"style/assets/full-web/holkham_wood.jpg"),    
    array("title"=>"Infinity Pier",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 18,
        "thumbnail"=>"style/assets/thumbnails/infinity_pier.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/infinity_pier.jpg",
        "full-image"=>"style/assets/full-web/infinity_pier.jpg"),    
    array("title"=>"Lake Windermere",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 19,
        "thumbnail"=>"style/assets/thumbnails/lake_windermere.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style//assets/half-web/lake_windermere.jpg",
        "full-image"=>"style/assets/full-web/lake_windermere.jpg"),    
    array("title"=>"Lakes Wall",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 20,
        "thumbnail"=>"style/assets/thumbnails/lakes_wall1.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/lakes_wall1.jpg",
        "full-image"=>"style/assets/full-web/lakes_wall1.jpg"),    
    array("title"=>"Misty Sunset",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 21,
        "thumbnail"=>"style/assets/thumbnails/misty_sunset.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/misty_sunset.jpg",
        "full-image"=>"style/assets/full-web/misty_sunset.jpg"),    
    array("title"=>"Moss Gate Lakes",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 22,
        "thumbnail"=>"style/assets/thumbnails/moss_gate_lakes.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/moss_gate_lakes.jpg",
        "full-image"=>"style/assets/full-web/moss_gate_lakes.jpg"),    
    array("title"=>"Rapeseed Flower",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 23,
        "thumbnail"=>"style/assets/thumbnails/rapeseed_flower.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/rapeseed_flower.jpg",
        "full-image"=>"style/assets/full-web/rapeseed_flower.jpg"),    
    array("title"=>"Seed Pod Sky",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 24,
        "thumbnail"=>"style/assets/thumbnails/seed_pod_sky.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style//assets/half-web/seed_pod_sky.jpg",
        "full-image"=>"style/assets/full-web/seed_pod_sky.jpg"),    
    array("title"=>"Shadows In the Sand",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 25,
        "thumbnail"=>"style/assets/thumbnails/shadows_in_the_sand.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/shadows_in_the_sand.jpg",
        "full-image"=>"style/assets/full-web/shadows_in_the_sand.jpg"),    
    array("title"=>"Sid",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 26,
        "thumbnail"=>"style/assets/thumbnails/sid.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/sid.jpg",
        "full-image"=>"style/assets/full-web/sid.jpg"),    
    array("title"=>"Spring Sky",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 27,
        "thumbnail"=>"style/assets/thumbnails/spring_sky.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/spring_sky.jpg",
        "full-image"=>"style/assets/full-web/spring_sky.jpg"),    
    array("title"=>"Stem Dance",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 28,
        "thumbnail"=>"style/assets/thumbnails/stem_dance.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/stem_dance.jpg",
        "full-image"=>"style/assets/full-web/stem_dance.jpg"),    
    array("title"=>"Sunset Glow",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 29,
        "thumbnail"=>"style/assets/thumbnails/sunset_glow.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/sunset_glow.jpg",
        "full-image"=>"style/assets/full-web/sunset_glow.jpg"),    
    array("title"=>"The Lakes From A Wall",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 30,
        "thumbnail"=>"style/assets/thumbnails/the_lakes_from_a_wall.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/the_lakes_from_a_wall.jpg",
        "full-image"=>"style/assets/full-web/the_lakes_from_a_wall.jpg"),    
    array("title"=>"Thistle Field",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 31,
        "thumbnail"=>"style/assets/thumbnails/thistle_field.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/thistle_field.jpg",
        "full-image"=>"style/assets/full-web/thistle_field.jpg"),    
    array("title"=>"View From A Tree",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 32,
        "thumbnail"=>"style/assets/thumbnails/view_from_a_tree.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/view_from_a_tree.jpg",
        "full-image"=>"style/assets/full-web/view_from_a_tree.jpg"),    
    array("title"=>"Walderswick Beach",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 33,
        "thumbnail"=>"style/assets/thumbnails/walderswick_beach.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/walderswick_beach.jpg",
        "full-image"=>"style/assets/full-web/walderwick_beach.jpg"),    
    array("title"=>"Walderswick Dunes",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 34,
        "thumbnail"=>"style/assets/thumbnails/walderswick_dunes.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style/assets/half-web/walderswick_dunes.jpg",
        "full-image"=>"style/assets/full-web/walderswick_dunes.jpg"),    
    array("title"=>"Wave Break",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 35,
        "thumbnail"=>"style/assets/thumbnails/wave_break.jpg",
        "orientation"=>"thumb-land",
        "feature-image"=>"style/assets/half-web/wave_break.jpg",
        "full-image"=>"style/assets/full-web/wave_break.jpg"),
    array("title"=>"Winter Dawn",
        "subtitle"=>"",
        "description"=>"",
        "link"=> 36,
        "thumbnail"=>"style/assets/thumbnails/winter_dawn.jpg",
        "orientation"=>"thumb-port",
        "feature-image"=>"style//assets/half-web/winter_dawn.jpg",
        "full-image"=>"style/assets/full-web/winter_dawn.jpg")       

);



$customer = array (
    array ("name" => "Joe Bloggs",
    "email" => "joe@bloggs.com",
    "password" => "toffee16",
    "d-add-line1" => "99, Somewhere Ave,",
    "d-add-line2" => "Long Town,",
    "d-add-city" => "Small Citi",
    "d-add-county" => "Herex",
    "d-add-pcode" => "ZZ999ZZ",
    "i-add-line1" => "99, Somewhere Ave,",
    "i-add-line2" => "Long Town,",
    "i-add-city" => "Small Citi",
    "i-add-county" => "Herex",
    "i-add-pcode" => "ZZ999ZZ",
    )
);

$orders = array (
    array (
        "order-ref" => "123-12421-12432",
        "email" => "joe@bloggs.com",
        "status" => "processing",
        "del-charge" => 9.99,
        )       
);

$order_lines = array (
    array (
        "image" => "Barley Sunset", "order-ref" => "123-12421-12432","type" => "A4", "price" => 14.99,
        "image" => "Shadows","order-ref" => "123-12421-12432", "type" => "A3","price" => 19.99,
    )
);

$admin_members = array (
    array (
        "name" => "Dean Middleton",
        "username" => "dean.middleton.dm@gmail.com",
        "password" => "clover08",
    )
);

$bloggs = array (
    array (
        "ref" => 1,
        "title" => "Blogg number 1",
        "date" => "01/01/2022",
        "content" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reprehenderit nulla, laudantium sunt accusantium asperiores earum facere velit libero sequi molestiae tempore blanditiis. Consequatur, quia eius nam unde blanditiis expedita animi.",
        "visible" => 0,
        "image" => "style/assets/half-web/blanket_of_snow.jpg",
    )
);

$events = array (
    array (
        "ref" => 1,
        "title" => "Great Events",
        "location" => "Somewhere",
        "date" => "01/01/2022",
        "content" => "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Reprehenderit nulla, laudantium sunt accusantium asperiores earum facere velit libero sequi molestiae tempore blanditiis. Consequatur, quia eius nam unde blanditiis expedita animi.",
        "visible" => 0,
        "image" => "style/assets/half-web/blanket_of_snow.jpg",
    )
);


$A4 = 14.99;
$A3 = 29.99;
$A2 = 59.99;
$A1 = 119.99;
$other = 1.00;
$postPacking = 9.99;


require_once('db_auth.php');

  function db_connect() {
    $connection = mysqli_connect(DB_SERVER, DB_USER, DB_PASS, DB_NAME);
    confirm_db_connect();
    return $connection;
  }

  function db_disconnect($connection) {
    if(isset($connection)) {
      mysqli_close($connection);
    }
  }

  function db_escape($connection, $string) {
    return mysqli_real_escape_string($connection, $string);
  }

  function confirm_db_connect() {
    if(mysqli_connect_errno()) {
      $msg = "Database connection failed: ";
      $msg .= mysqli_connect_error();
      $msg .= " (" . mysqli_connect_errno() . ")";
      exit($msg);
    }
  }

  function confirm_result_set($result_set) {
    if (!$result_set) {
    	exit("Database query failed.");
    }
  }



  $product_type = array (
    array("type"=>"A4",
        "description"=>"Open Edition Print, 297mm x 210mm",
        "price"=> 14.99),
    array("type"=>"A3",
        "description"=>"Limited Edition Print, 420mm x 297mm",
        "price"=> 29.99),
    array("type"=>"A2",
        "description"=>"Limited Edition Print, 594mm x 420mm",
        "price"=> 59.99),
    array("type"=>"A1",
        "description"=>"Limited Edition Print, 841mm x 594mm",
        "price"=> 119.99),
    // array("type"=>"Multipack",
    //     "description"=>"This isnt a multiPack",
    //     "price"=> 890.01),
    array("type"=>"other",
        "description"=>"Another Product",
        "price"=> 1.00),
        
);